<script lang="ts">
	import '../app.css';
	import { page } from '$app/state';
	import Button from '$lib/client/components/ui/button/button.svelte';
	import { PlusIcon, LogOutIcon } from 'lucide-svelte';
	import * as Tooltip from '$lib/client/components/ui/tooltip';
	let { children } = $props();
</script>

<svelte:head>
	<title>Seven Minute Workouts</title>
	<style>
		@import url('https://fonts.googleapis.com/css2?family=Geist+Mono&family=Figtree&family=Geist:wght@100..900&family=Gloock&display=swap');
	</style>
	<link rel="icon" href="/favicon.png" />
	<meta name="robots" content="index, follow" />
	<meta
		name="description"
		content="Seven minute workouts generated by AI. Stop thinking about working out and just do it."
	/>
	<meta property="og:title" content="Seven Minute Workouts" />
	<meta
		property="og:description"
		content="Seven minute workouts generated by AI. Stop thinking about working out and just do it."
	/>
	<meta property="og:type" content="website" />
	<meta property="og:image" content="https://sevenminuteworkouts.com/favicon.png" />
	<meta property="og:image:width" content="256" />
	<meta property="og:image:height" content="256" />
	<meta property="og:url" content="https://sevenminuteworkouts.com" />
	<meta property="og:site_name" content="Seven Minute Workouts" />
	<link rel="canonical" href={page.url.href.replace(page.url.origin, 'https://sevenminuteworkouts.com')} />
	<meta property="og:image" content="https://sevenminuteworkouts.com/favicon.png" />
	<meta property="og:image:width" content="256" />
	<meta property="og:image:height" content="256" />
	<!-- <meta name="theme-color" content="#B02054" /> -->
	<meta name="theme-color" content="#020617" />
</svelte:head>

<div class="overscroll-y-contain bg-slate-950">
	<div class="sticky inset-0 bottom-auto w-full">
		<div
			class="mx-auto flex w-full max-w-screen-lg flex-row items-center justify-center px-4 py-2"
		>
			<a href="/" class="rounded-md bg-slate-950 px-2 py-0.5">
				<span class="font-bold text-3xl">Seven Minute Workouts</span>
			</a>
		</div>
	</div>
	{@render children()}
</div>

<style>
	:global(body),
	:global(body *) {
		font-family: 'Geist', sans-serif;
	}
</style>
