<script lang="ts">
	import '../app.css';
	import { page } from '$app/state';
	let { children } = $props();
</script>

<svelte:head>
	<title>Seven Minute Workouts</title>
	<style>
		@import url('https://fonts.googleapis.com/css2?family=Geist+Mono&family=Figtree&family=Geist:wght@100..900&family=Gloock&display=swap');
	</style>
	<link rel="icon" href="/favicon.png" />
	<meta name="robots" content="index, follow" />
	<meta
		name="description"
		content="Seven minute workouts generated by AI. Stop thinking about working out and just do it."
	/>
	<meta property="og:title" content="Seven Minute Workouts" />
	<meta
		property="og:description"
		content="Seven minute workouts generated by AI. Stop thinking about working out and just do it."
	/>
	<meta property="og:type" content="website" />
	<meta property="og:image" content="https://sevenminuteworkouts.com/favicon.png" />
	<meta property="og:image:width" content="256" />
	<meta property="og:image:height" content="256" />
	<meta property="og:url" content="https://sevenminuteworkouts.com" />
	<meta property="og:site_name" content="Seven Minute Workouts" />
	<link
		rel="canonical"
		href={page.url.href.replace(page.url.origin, 'https://sevenminuteworkouts.com')}
	/>
	<meta property="og:image" content="https://sevenminuteworkouts.com/favicon.png" />
	<meta property="og:image:width" content="256" />
	<meta property="og:image:height" content="256" />
	<!-- <meta name="theme-color" content="#B02054" /> -->
	<meta name="theme-color" content="#020617" />
</svelte:head>

<div class="overscroll-y-contain bg-slate-950">
	<div class="fixed inset-0 bottom-auto w-full">
		<div class="mx-auto flex w-full max-w-screen-lg flex-row items-center justify-start gap-2 p-2">
			<a href="/" class="rounded-md">
				<img src="/favicon.png" alt="logo" class="h-8 w-auto rounded-md" />
			</a>
		</div>
	</div>
	{@render children()}
</div>

<style>
	:global(body),
	:global(body *) {
		font-family: 'Geist', sans-serif;
	}
</style>
